### ISSUE TITLE
pantalla producto - botones

### ISSUE THREAD

**Issue by OliverMartinezH** [mrpuck/easy#3]
El estilo del botón "calculadora de materiales" no tiene la manito al hacer hover.

Ademas al apretar cualquiera de los 3 botones de la pantalla no se produce ningún efecto visual.

**Comment by mrpuck** [comment]
Se cambia el botón "Calculadora de materiales" de "div" a "a". La maqueta no comprende comportamientos; se ignora segundo issue reportado.
