### ISSUE TITLE
Pagina Producto, Error combo meses con firefox

### ISSUE THREAD

**Issue by OliverMartinezH** [mrpuck/easy#4]
El combo de meses se ve raro con firefox.

![product_error combo cuotas firefox](https://cloud.githubusercontent.com/assets/13038650/8598872/a8285c9c-2633-11e5-97b8-070fe7eca027.JPG)

**Comment by mrpuck** [comment]
Estimado, favor validar que la sintáxis HTML del selector sea la misma en
ambos casos.

Saludos

http://www.mrpuck.net/ http://www.mrpuck.net/
Alexis Vásquez

Senior Developer@mrpuck http://www.twitter.com/mrpuck

Mail:yo@mrpuck.net

Teléfono:+569 7 900 71 45

Sitio web:www.mrpuck.net

**Comment by OliverMartinezH** [comment]
es la misma, de hecho caso también sucede con el prototipo.

**Comment by mrpuck** [comment]
Corregido. Será liberado en el prox. Release.
