### ISSUE TITLE
Despacho - Dimension 800 * 1280 px

### ISSUE THREAD

**Issue by OliverMartinezH** [mrpuck/easy#5]
En el "seudo" header de la pagina de despacho, la flecha "Confirmacion" queda debajo de las demas, deformando el encabezado.

![image](https://cloud.githubusercontent.com/assets/13038650/8704808/dac8d862-2afb-11e5-8a8d-94022f2b213f.png)

Ademas, tenemos la duda de que pasa con las otras 2 etapas del menu superior (pago y confirmacion)

**Comment by mrpuck** [comment]
Coregido. 
Las otras 2 etapas son parte de la misma página y debería marcar el paso adecuado según corresponda.
