### ISSUE TITLE
Pagina de Producto PDP - agregar a lista de deseos no debe estar centrado.

### ISSUE THREAD

**Issue by OliverMartinezH** [mrpuck/easy#8]
Segun el PDF el link agregar a la lista de deseos debe estar orientado a la derecha, no al centro.

![image](https://cloud.githubusercontent.com/assets/13038650/8756311/b76b8a74-2ca7-11e5-9fa3-18c0a988ded9.png)

**Comment by mrpuck** [comment]
Corregido
